name: CI
on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   tests:
      name: "ubuntu"
      timeout-minutes: 60
      strategy:
        fail-fast: false
        matrix:
          os: ['ubunut-latest']
          sys:
            - { compiler: 'gcc', version: '9'}
            - { compiler: 'gcc', version: '10'}
            - { compiler: 'gcc', version: '11'}
            - { compiler: 'gcc', version: '12'}
            - { compiler: 'gcc', version: '13'}
            - { compiler: 'gcc', version: '14'}
            - { compiler: 'clang', version: '14'}
            - { compiler: 'clang', version: '15'}
            - { compiler: 'clang', version: '16'}
            - { compiler: 'clang', version: '17'}
            - { compiler: 'clang', version: '18'}
          include:
            - os: 'ubuntu-22.04'
              sys: { compiler: 'clang', version: '11'}
            - os: 'ubuntu-22.04'
              sys: { compiler: 'clang', version: '12'}
            - os: 'ubuntu-22.04'
              sys: { compiler: 'clang', version: '13'}
      runs-on: ${{ matrix.os }}
      steps:
         - name: "Checkout HPCombi repo . . ."
           uses: actions/checkout@v3
         - name: "Setup compiler . . ."
           if: ${{ matrix.sys.compiler == 'gcc' }}
           run: |
             GCC_VERSION=${{ matrix.sys.version }}
             sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
             sudo apt-get --yes update
             sudo apt-get install gcc-$GCC_VERSION g++-$GCC_VERSION
             CC=gcc-$GCC_VERSION
             echo "CC=$CC" >> $GITHUB_ENV
             CXX=g++-$GCC_VERSION
             echo "CXX=$CXX" >> $GITHUB_ENV
         - name: "Setup compiler . . ."
           if: ${{ matrix.sys.compiler == 'clang' }}
           run: |
             LLVM_VERSION=${{ matrix.sys.version }}
             sudo apt-get --yes update
             sudo apt-get install --yes clang++-$LLVM_VERSION
             CC=clang-$LLVM_VERSION
             echo "CC=$CC" >> $GITHUB_ENV
             CXX=clang++-$LLVM_VERSION
             echo "CXX=$CXX" >> $GITHUB_ENV
         - name: "Install dependencies . . ."
           run: |
             sudo apt-get install --yes ccache
         - name: "Configure the HPCombi build . . ."
           env:
             CC: ${{ env.CC }}
             CXX: ${{ env.CXX }}
           run: |
             mkdir build
             cd build
             cmake -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
         - name: "Build HPCombi . . ."
           run: |
             cd build/tests
             make -j4
         - name: "Run HPCombi tests . . ."
           run: |
             cd build/tests
             ./test_all
